# Generated by Django 3.1.7 on 2021-04-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
